### ISSUE TITLE
Not adding data

### ISSUE THREAD

**Issue by benwhalley** [NicoWeio/aw-watcher-atom#2]
I've just installed this package, but it doesn't seem to be sending data to AW. Where should I be looking to debug this? Is there a way to send a test event?

**Comment by NicoWeio** [comment]
I'm afraid I didn't make it clear in the description that this watcher only sends data (so-called heartbeats) to the AW server when you **actively** use the code editor, i.e. you type. Could that be what threw you off?
Apart from that, I am not really sure how you would go about debugging. You could try bringing up the DevTools using <kbd>Ctrl+Shift+I</kbd> and looking at the Console & Network tabs. You _should_ see no logs but regular network requests to the AW server.

**Comment by benwhalley** [comment]
Thanks. I tried updating to the latest Atom and it's working now (1.57.0 didn't work, 1.58 does on latest OSX).

**Comment by NicoWeio** [comment]
Interesting, thank you for letting me know. I'll keep that in mind if others encounter similar problems.
